---
author: "YannisMarkonis"
date: "April 5, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Download MSWEP only for Europe

This script downloads the global [MSWEP](http://www.gloh2o.org/) dataset and keeps only precipitation over a certain area due to its huge size. 

It consists of a loop that:

* defines the file that should be downloaded
* downloads it
* opens the netcdf file
* partitions the area
* transforms it to a data.table in tidy format
* adds it to the end of the data.table

Check also http://climvis.de/read-plot-netcdf-files-r/

```{r paths, libraries and functions}
nc.path = "C:/Users/markonis/Documents/R/Projects/RUserGroup/Members/Yannis/MSWEP"
shp.path = "C:/Users/markonis/Documents/R/Projects/OWDA"
out.path = "C:/Users/markonis/Documents/R/Projects/RUserGroup/Members/Yannis/MSWEP"
my.crs = "+proj=longlat +ellps=WGS84"

library(data.table)
library(ncdf4)
library(raster)
library(maptools)
library(RCurl) 
library(foreach)
library(doParallel)

nc.brick = function(nc.file, lon, lat, path = nc.path, nc.crs = my.crs) { #opens netcdf file as a raster brick and crops it
  aa = file.path(path, nc.file)
  aa = brick(aa, crs = nc.crs) #following Martin's way: faster, less code, less ram
  br.names = aa@data@names
  aa = crop(aa, extent(c(-rev(lat),lon))) #these manipulations are due to the fact that raster do not correspond to ncdf (see below)
  aa = flip(t(aa), direction = 1) #we have to rotate and flip the data 
  aa = setExtent(aa, extent(c(lon,lat))) #and then insert the correct coordinations [this manipulation saves some time]
  aa@data@names = br.names 
  return(aa)
}

#This is for parallel computing
bindToEnv <- function(bindTargetEnv=parent.frame(),objNames,doNotRebind=c()) {
  # Bind the values into environment
  # and switch any functions to this environment!
  for(var in objNames) {
    val <- get(var,envir=parent.frame())
    if(is.function(val) && (!(var %in% doNotRebind))) {
      # replace function's lexical environment with our target (DANGEROUS)
      environment(val) <- bindTargetEnv
    }
    # assign object to target environment, only after any possible alteration
    assign(var,val,envir=bindTargetEnv)
  }
}
```

```{r download initialization}
login.id = "e2o_guest"
login.pwd = "oowee3WeifuY1aeb"

mswep.url = paste("ftp://",login.id,":",login.pwd,"@wci.earth2observe.eu/data/primary/public/jrc/MSWEP_V1.2/3hourly/", sep = "")
ftp.files = getURL(mswep.url, dirlistonly = TRUE) #Get all filenames in ftp address
ftp.files = unlist(strsplit(ftp.files, "\r\n")) 

 # binary file types are transferred with mode = "wb".
```

```{r main}
lat = c(34.25, 60.25) 
lon = c(-10.75, 38.25) 

#Download per month: we will create bigger ncdf files later
for(i in 1:length(ftp.files)){
  download.file(paste(mswep.url, ftp.files[i], sep =""), "imp_month.nc", mode = "wb")
  mswep.ras.eu = nc.brick('imp_month.nc', lon, lat)
  writeRaster(mswep.ras.eu, ftp.files[i], varname= "precipitation", varunit = "mm",  zname = "time", overwrite=TRUE) 
  print(i)
}
```

```{r Validation of function for the single file}
world.shp = readShapeLines(file.path(shp.path, "ne_50m_admin_0_countries_lakes.shp"), proj4string=CRS(my.crs)) 

plot(mswep.ras.eu$X1979.01.01.00.00.00)  
plot(world.shp, col="black", add=TRUE) 
```

```{r Let's make a big netcdf - or not}
f = list.files("Data")
f = sapply(f, function(x) paste("Data/", x, sep = ""))
r <- raster(f[1], band)
s <- stack(r)
s@layers <- sapply(f, function(x) { r@file@name=x; r } ) 
addLayer(tmp, brick(f[2]))
mswep.brk.eu <- brick(f[1]) # create first brick
for (i in 2:2) {
  mswep.brk.eu = addLayer(mswep.brk.eu, brick(f[i]))
print(i)
  }

mswep.brk.cz = crop(mswep.brk.eu, extent(cz.cords))  
writeRaster(mswep.brk.cz, 'MSWEP_CZ.nc', varname= "precipitation", varunit = "mm",  zname = "time", overwrite=TRUE) 
```

```{r The RDS file}
mswep = as.data.table.raster(mswep.ras.eu)

#names(mswep) = seq(as.POSIXct(paste(1979+i,"-01-01 00:00:00", sep = ""), tz="UTC"), as.POSIXct(paste(1979+i,"-12-31 21:00:00",sep = ""),  tz="UTC"), by = "3 hours") this has to be modified, kept it just to remember the whole idea

saveRDS(mswep, "EuropeMSWEP.rds") # File is approx 20MB (?)
```

```{r Work in a smaller region and lets go parallel} 
cz.cords = c(12.25 , 19.25, 48.25, 51.25) #Fortunately, the total size of CR is estimated at 150MB :)

#Normal way 
mswep.ras.cz = brick('data/197901.nc')
mswep.ras.cz = crop(mswep.ras.cz, extent(cz.cords))
for(i in 2:length(ftp.files)){
  mswep.ras.cz.tmp = brick(paste('data/', ftp.files[i], sep = ""))
  mswep.ras.cz.tmp = crop(mswep.ras.cz.tmp, extent(cz.cords))
  mswep.ras.cz= addLayer(mswep.ras.cz, mswep.ras.cz.tmp)
  print(i)
}

#setup parallel backend to use many processors
cl <- makeCluster(detectCores()-1) 
registerDoParallel(cl)
mswep.ras.cz = brick('data/197901.nc')
mswep.ras.cz = crop(mswep.ras.cz, extent(cz.cords))

mswep.ras.cz = foreach(i=1:length(ftp.files),
        .combine = addLayer,
        .packages='raster') %dopar% {
  crop(brick(paste('data/', ftp.files[i], sep = "")), extent(cz.cords))
}
stopCluster(cl)
names(mswep.ras.cz) = 1:108112
save(mswep.ras.cz, file = "mswep_cz.Rdata")
writeRaster(mswep.ras.cz, 'mswep_cz.nc', varname= "precipitation", varunit = "mm",  zname = "time", overwrite=TRUE) 

```



